version: 2.1

orbs:
  python: circleci/python@1.2.0
  
workflows:
  main:
    jobs:
      steps:
        - python/install-packages:
            pip-dependency-file: requirements.txt
            pkg-manager: pip
        - python/test:
            pkg-manager: pip-dist
            test-tool: pytest
