version: 2.1

orbs:
  python: circleci/python@1.3.1
  
workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: pip-dist
          pip-dependency-file: requirements.txt
          test-tool: pytest
