version: 2.1

orbs:
  python: circleci/python@1.2.0
  
workflows:
  main:
    jobs:
      - python/test:
        pip-dependency-file: requirements.txt
        pkg-manager: pip-dist
        test-tool: pytest
