version: 2.1

orbs:
  python: circleci/python@1.2.1

workflows:
  main:
    jobs:
      - python/test:
          test-tool: pytest
          args: '--dev'
          pkg-manager: pipenv
          setup:
            - run: pip install pytest
